config/routes.rb
Rails.application.routes.draw do
 
    get 'top/main'
    post 'top/login'
    
    root 'top#main'
    get  'top/logout'
    
    resources :users, only: [:index, :new, :create, :destroy]
    
    root 'users#index'
#    get "application/L4"
#root "application#L4"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
   
    def self.authenticate(uid, pass)
        user = find_by(uid: uid)
        if user and BCrypt::Password.new(user.pass) == pass
            true
        else
            false
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def L4
   session[:c] ||= 0 #遅延初期化というテク。ぜひ覚えて欲しい。
   session[:c] = session[:c].to_i + 1
   render plain: session[:c]
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid]
     render :main
    else
        render :login
        
    
    end
  end


 def login
    if User.authenticate(params[:uid], params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      render :error
    end
 end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def index
    @users = User.all
   end

  def new
    @user = User.new
  end
  
  def create
    p = BCrypt::Password.create(params[:user][:pass])
    @user = User.new(uid: params[:user][:uid], pass: p)
    if @user.save
      flash[:info] = "ユーザを登録しました"
      redirect_to users_path
    else
      @user.pass = ""
      render :new
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:info] = "ユーザを削除しました"
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
ログイン失敗です！

<p>
<%= link_to '戻る', :back %>
</p>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/top/main.html.erb
ログイン中です!

<p><%= link_to 'ログアウト', top_logout_path %></p>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% if flash[:info] %>
  <font color="green"><%= flash[:info] %></font>
<% end %>

<% @users.each do |e| %>
  <p>
      <%= e.uid %>
      <%= link_to '削除', user_path(e), method: :delete %>
  </p>
<% end %>

<hr>

<%= link_to 'ユーザー追加', new_user_path %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<% if @user.errors.present? %>
<font color="red">
    <h3>エラーがあります</h3>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
    </font>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
<p>  
    <%= f.label :uid, 'ユーザーID' %>
    <%= f.text_field :uid %></p>
<p>
    <%= f.label :pass, 'パスワード' %>
    <%= f.text_field :pass %></p>
<p>
    <%= f.submit '登録' %>
</p>
<% end %>